---
title: "Lab_06"
author: "Sunday Okechukwu"
date: "2023-02-21"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Question 1

```{r}
 Xm <- matrix(c(1, 4,
                1, 1,
                1, 2,
                1, 3,
                1, 3,
               1, 4), ncol = 2, byrow = TRUE)
```


```{r}
 Ym <- matrix(c(16,
                5,
                10,
                15,
                13,
                22), ncol = 1, byrow = TRUE)
```

```{r}
t(Ym) %*% Ym
```
```{r}
t(Xm) %*% Xm
```

```{r}
t(Xm) %*% Ym
```

# Question 2
```{r}

R <- matrix(c(25,
              12), ncol = 1, byrow = TRUE)

Q <- matrix(c(4, 7,
              2, 3), ncol = 2, byrow = TRUE)
```
```{r}
 solve(Q)
```

```{r}
 solve(Q)%*%R
```

# Question 3


```{r}
 Xm <- matrix(c(1, 49,
                1, 69,
                1, 89,
                1, 99,
                1, 109), ncol = 2, byrow = TRUE)
```

```{r}
  Ym <- matrix(c(124,
                 95,
                71,
                45,
                18), ncol = 1, byrow = TRUE)
```

A = (X^T*X)^-1*X^TY

```{r}
t(Xm) -> transposeXm

transposeXm%*%Xm-> ProDuct1
```

```{r}
 det(ProDuct1)
```
```{r}
solve(ProDuct1)
```

```{r}
solve(ProDuct1)%*%transposeXm%*%Ym
```
```{r}
solve(ProDuct1)%*%transposeXm%*%Ym -> interceptandslope
  interceptandslope
```
```{r}
#Fitted values
 Xm %*% interceptandslope
```
```{r}
#Residuals
Ym -  Xm %*% interceptandslope
```


